name: AI Model Interaction

# Defines when the action will run. 
on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  interaction:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Sets up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run the scripts
      - name: Run Authentication
        run: python Authentication.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run Model Listing and Selection
        run: python Model_Listing_and_Selection.py

      - name: Run User Input Enhancement
        run: python User_Input_Enhancement.py

      - name: Run Session Data Management
        run: python Session_Data_Management.py

      - name: Run Advanced Interaction Features
        run: python Advanced_Interaction_Features.py

      # Add other scripts as needed
      # - name: Run Other Script
      #   run: python your_script.py
